### ISSUE TITLE
add a option to copy the css of card too

### ISSUE THREAD

**Issue by piyushkdas0611** [piyushkdas0611/Profile-Card-Generator#13]

**Comment by MagnusVV** [comment]
Hello piyushkdas0611,

Interesting issue. Do you mean that you'd like an extra button on each card that's labeled something like "Copy CSS"?

**Comment by piyushkdas0611** [comment]
> Hello piyushkdas0611,
> 
> Interesting issue. Do you mean that you'd like an extra button on each card that's labeled something like "Copy CSS"?

Yes, exactly that

**Comment by MagnusVV** [comment]
Thank you, piyushkdas0611.

I would like to give this a try. Could you please assign me to this?

**Comment by Subrat29** [comment]
I'd like to work on this issue. Could you please assign it to me?

**Comment by piyushkdas0611** [comment]
> Thank you, piyushkdas0611.
> 
> I would like to give this a try. Could you please assign me to this?

sure go for it

**Comment by MagnusVV** [comment]
There is now a pull request with the modified code.
