### ISSUE TITLE
bug on hover specific card

### ISSUE THREAD

**Issue by vessaldaneshvar** [piyushkdas0611/Profile-Card-Generator#19]
hi
i found new bug when using profile generator.
describing the bug is difficult.
i taked video that show bugs.

https://github.com/piyushkdas0611/Profile-Card-Generator/assets/52780555/ffdce133-044b-44c7-a9d2-a74fe085190c

**Comment by piyushkdas0611** [comment]
Thanks for mentioning about this. If anyone would like to look into this issue most welcome

**Comment by arezooHND** [comment]
Hi, please assign this issue to me.
