### ISSUE TITLE
[UI Improve] I would like to improve the UI of the Home page

### ISSUE THREAD

**Issue by imsp18** [piyushkdas0611/Profile-Card-Generator#20]
<h3>Changes suggested?</h3>

-  Would like to change the home page screen's UI to make it more user friendly 

<h3>Screenshots </h3>

Design of the Suggested changes 👇

![image](https://github.com/piyushkdas0611/Profile-Card-Generator/assets/108970936/8c58f1d3-e491-4967-96fb-2c81f11b584a)

**Comment by piyushkdas0611** [comment]
sure that's cool, if you could design a dark mode, would be cooler

**Comment by imsp18** [comment]
ok, will change the background to darker theme
