### ISSUE TITLE
add a footer section

### ISSUE THREAD

**Issue by piyushkdas0611** [piyushkdas0611/Profile-Card-Generator#22]
add a footer section, with the text this project is participating in hacktoberfest and copywrite 2023

**Comment by cyberdad68** [comment]
i would like to work on this issue,Could you assign me this.

**Comment by piyushkdas0611** [comment]
sure go for it

**Comment by ramchandra06032004** [comment]
hello sir i would like to contribute in your project i can make good attractive footer ,please assign it to me
