### ISSUE TITLE
Form is unresponsive on mobile views

### ISSUE THREAD

**Issue by Bsodoge** [piyushkdas0611/Profile-Card-Generator#31]
Currently the form is extremely small on small screens as seen below.

![image](https://github.com/piyushkdas0611/Profile-Card-Generator/assets/79531561/dddffc6d-29be-4a96-9800-5833ead04906)

This can be solved using media querys and responsive CSS, please assign this issue to me.

**Comment by piyushkdas0611** [comment]
sure go for it
